# BioSimulation 1 01

FROM naito/miniconda-ecell3:latest

MAINTAINER Yasuhiro Naito <ynaito@sfc.keio.ac.jp>
LABEL version="0.1"

RUN mkdir /notebooks/BioSim1-01
COPY BioSim1-01/* /notebooks/BioSim1-01/
