# BioSimulation 1 00 Screening Assignment

FROM naito/miniconda-ecell3:latest

MAINTAINER Yasuhiro Naito <ynaito@sfc.keio.ac.jp>
LABEL version="0.2"

RUN mkdir /notebooks/BioSim1-00
COPY BioSim1-00/* /notebooks/BioSim1-00/
